const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Acts.PlayByName
	];
};
self.C3_JsPropNameTable = [
	{btnBasla: 0},
	{btnBilgi: 0},
	{btnButonlar: 0},
	{Sine: 0},
	{btnDevam: 0},
	{kapla: 0},
	{btnFullScreen: 0},
	{btnHome: 0},
	{btnKapat: 0},
	{btnKaynakca: 0},
	{durum: 0},
	{btnMuzik: 0},
	{btnSes: 0},
	{oyunBasla: 0},
	{btnTekrar: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{gameBackground: 0},
	{home: 0},
	{bilgisayfa: 0},
	{picture: 0},
	{words: 0},
	{a: 0},
	{Flash: 0},
	{cember: 0},
	{sonuc: 0},
	{dizi: 0},
	{dogru: 0},
	{gecisEkran: 0},
	{butonlarSayfa: 0},
	{kaynakca: 0},
	{game2: 0},
	{b: 0},
	{words2: 0},
	{yonerge2: 0},
	{ogretmen: 0},
	{metinler: 0},
	{dizi2: 0},
	{endSayfa: 0},
	{cemberWords: 0},
	{cemberSonuc: 0},
	{dogruYanlis2: 0},
	{c: 0},
	{yildiz: 0},
	{yanlis: 0},
	{Particles: 0},
	{butonlar: 0},
	{randomword: 0},
	{x: 0},
	{basla: 0},
	{randomMetin: 0},
	{y: 0},
	{dogru2: 0},
	{tiklama: 0},
	{muzik_adi: 0},
	{muzik_sure: 0}
];

self.InstanceType = {
	btnBasla: class extends self.ISpriteInstance {},
	btnBilgi: class extends self.ISpriteInstance {},
	btnButonlar: class extends self.ISpriteInstance {},
	btnDevam: class extends self.ISpriteInstance {},
	btnFullScreen: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnKapat: class extends self.ISpriteInstance {},
	btnKaynakca: class extends self.ISpriteInstance {},
	btnMuzik: class extends self.ISpriteInstance {},
	btnSes: class extends self.ISpriteInstance {},
	oyunBasla: class extends self.ISpriteInstance {},
	btnTekrar: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	gameBackground: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	bilgisayfa: class extends self.ISpriteInstance {},
	picture: class extends self.ISpriteInstance {},
	words: class extends self.ISpriteInstance {},
	cember: class extends self.ISpriteInstance {},
	sonuc: class extends self.ISpriteInstance {},
	dizi: class extends self.IArrayInstance {},
	dogru: class extends self.ISpriteInstance {},
	gecisEkran: class extends self.ISpriteInstance {},
	butonlarSayfa: class extends self.ISpriteInstance {},
	kaynakca: class extends self.ISpriteInstance {},
	game2: class extends self.ISpriteInstance {},
	words2: class extends self.ISpriteInstance {},
	yonerge2: class extends self.ISpriteInstance {},
	ogretmen: class extends self.ISpriteInstance {},
	metinler: class extends self.ISpriteInstance {},
	dizi2: class extends self.IArrayInstance {},
	endSayfa: class extends self.ISpriteInstance {},
	cemberWords: class extends self.ISpriteInstance {},
	cemberSonuc: class extends self.ISpriteInstance {},
	dogruYanlis2: class extends self.ISpriteInstance {},
	yildiz: class extends self.ISpriteInstance {},
	yanlis: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	butonlar: class extends self.ISpriteInstance {}
}